name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out your repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'maori-fishing-calendar/package-lock.json'

      - name: Install dependencies
        run: npm install
        working-directory: ./maori-fishing-calendar

      - name: Build Astro site
        run: npm run build
        working-directory: ./maori-fishing-calendar
        env:
            BASE_URL: /maori-fishing-calendar/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./maori-fishing-calendar/dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
