name: Deploy GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # 3. Install dependencies
      - name: Install dependencies
        run: npm install
        working-directory: .

      # 4. Set BASE_URL dynamically
      - name: Set BASE_URL
        id: base-url
        run: |
          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            echo "BASE_URL=/"
          else
            echo "BASE_URL=/pr-${{ github.event.pull_request.number }}/"
          fi
          echo "BASE_URL=$BASE_URL" >> $GITHUB_ENV

      # 5. Build Astro site
      - name: Build Astro site
        run: npm run build
        working-directory: .
        env:
          BASE_URL: ${{ env.BASE_URL }}

      # 6. Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          path: ./dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 7. Output preview URL if PR
      - name: Show preview URL
        if: github.event_name == 'pull_reque

